name: Test Docker

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Build
        run: |
          echo "Free space:"
          df -h
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          docker build -t rosetta .
      
      - name: Run
        run: |
          docker exec -i rosetta /bin/echo 'Hello world'
          