name: Test Docker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          docker build -t alpine .
      
      - name: Run
        run: |
          docker run -v $PWD:/data -i alpine /bin/echo /data/LICENSE
          
