name: Test dd

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sudo
        run: |
          useradd -m steven
          usermod -a -G sudo steven

      - name: Echo
        run: |
          echo "Free space:"
          df -h
      
      - name: dd
        run: |
          sudo dd if=/dev/zero of=/var/test bs=1M count=1000
      
      - name: Echo
        run: |
          echo "Free space:"
          df -h
          