name: Test Docker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Free space:"
          df -h
      
      - name: dd
        run: |
          dd if=/dev/zero of=/var/test bs=1M count=1000
      
      - name: Echo
        run: |
          echo "Free space:"
          df -h
          