name: Test Docker

on:
  push:
    - .github/workflows/TestDocker.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Free space:"
          df -h
          echo "I'm in:"
          pwd
        
      - name: Docker Info
        run: |
          docker info
          
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 
          swap-size-mb: 46080
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Echo
        run: |
          echo "Free space:"
          df -h
          echo "I'm in:"
          pwd
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          docker build -t alpine .
      
      - name: Run
        run: |
<<<<<<< HEAD
          docker run -i rosetta /bin/echo 'Hello world'
=======
          docker run -i alpine /bin/echo 'Hello world'
>>>>>>> 786d7dac50f22dff152d359f846ec9fc4bc2fcc7
          