name: testSSH

on:
  workflow_dispatch:

jobs:
  Synchronize:
    runs-on: ubuntu-latest
    steps:
      #- name: Change hosts
      #  run: |
      #    sudo echo "154.213.2.253        gitee.com" | sudo tee -a /etc/hosts

      - name: Add SSH keys
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEY }}

      #- name: Test Github
      #  run: |
      #    ssh -T git@github.com
      
      - name: Test Gitee
        run: |
          ssh -T git@gitee.com
