name: Test Docker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps: 
      - name: Test Docker
        run: |
          docker buildx create --name mybuilder
          docker buildx ls