name: Test Webhook

on:
  workflow_dispatch:
  repository_dispatch:
    types: hello

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: |
        echo Hello World!
