name: Test dd

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: File server
        run: |
          docker run -d \
            -v $PWD:/web \
            -p 8080:8080 \
            halverneus/static-file-server:latest
      
      - name: Test File server
        run: |
          curl http://127.0.0.1:8080
      
      - name: Build
        run: |
          docker build --network="host" -t rosetta - < Dockerfile

      - name: Test
        run: |
          docker run -i rosetta /bin/ash -c 'ls'
          