name: Test dd

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        run: |
          chmod +x build.sh
          ./build.sh
      
      - name: Run
        run: |
          curl -O http://127.0.0.1:28294/LICENSE
          