name: Test Docker

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Echo
        run: |
          echo "Free space:"
          df -h
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          docker build -t alpine .
      
      - name: Run
        run: |
          docker run -i alpine /bin/echo 'Hello world'
      
      - name: Package
        run: |
          $ docker save alpine | xz -9 > alpine-latest.tar.xz

      - name: Upload
          curl -fsSL git.io/file-transfer | bash
          ./transfer gof -s -p 64 --no-progress alpine-latest.tar.xz 2>&1 | tee gofile.log
          echo "::warning file=gofile.io::$(cat gofile.log | grep https)"
          echo "::set-output name=url::$(cat gofile.log | grep https | cut -f3 -d" ")"
          