name: Test Docker

on:
  workflow_dispatch:

jobs:
  Test_for_Docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          docker build -t rosetta .
      
      - name: Run
        run: |
          docker exec rosetta -it /bin/echo 'Hello world'
          